### ISSUE TITLE
filter duplicate descriptions

### ISSUE THREAD

**Issue by umlaeute** [spanezz/pkgquiz#5]
now that there is a `--hard` switch :tada:, some of the questions become almost impossible to answer:

> What is the description for package tomboy?
>   1) desktop note taking program using Wiki style links
>   2) desktop note taking program using Wiki style links
>   3) music player and organizer for GNOME
> Enter the number (q to quit): 
> 2
> Correct!

and

> What is the description for package noshell?
>   1) transitional dummy package
>   2) transitional dummy package
>   3) transitional dummy package
> Enter the number (q to quit): 1
> Incorrect!
> The correct answer was: transitional dummy package

**Comment by spanezz** [comment]
Should be fixed now
